apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: chameleon
spec:
  version: 7.13.0
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        volumes:
        - name: elasticsearch-data
          emptyDir:
             sizeLimit: 100Gi
        containers:
        - name: elasticsearch   
          resources:
              requests:
                memory: 100Gi
                cpu: 7
              limits:
                memory: 100Gi
                cpu: 7
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        nodeSelector:
          type: es
